### ISSUE TITLE
文章中提到的管理页面，在代码中没有？

### ISSUE THREAD

**Issue by young001** [lattebank/rate-limiter#6]
文章中提到的管理页面，在代码中没有？看到rate-limiter-server是没有管理页面的

**Comment by wukq** [comment]
是的，因为管理页面集成到了公司管理平台中，不好拆分。管理页面目前功能也比较简单，只有CRUD

**Comment by wukq** [comment]
是的，因为管理页面集成到了公司管理平台中，不好拆分。管理页面目前功能也比较简单，只有CRUD
