### ISSUE TITLE
锁的问题

### ISSUE THREAD

**Issue by ro9er** [lattebank/rate-limiter#7]
我有一个问题，就是本身在更新的时候是需要依赖锁的，guava的更新也是如此，否则在大并发的情况下会出现更新脏数据的情况，我看了下代码内部应该是没有做类似处理的？那机制是什么呢？通过lua？多机的时候怎么处理呢？

**Comment by wukq** [comment]
> 我有一个问题，就是本身在更新的时候是需要依赖锁的，guava的更新也是如此，否则在大并发的情况下会出现更新脏数据的情况，我看了下代码内部应该是没有做类似处理的？那机制是什么呢？通过lua？多机的时候怎么处理呢？

redis是单线程模型，lua在redis中的执行本身就是事务的。
