### ISSUE TITLE
想问下为什么更高的 qps (大于 5000) 就不行了?

### ISSUE THREAD

**Issue by Knight-Wu** [lattebank/rate-limiter#9]
更高的 qps 会有什么问题呢

**Comment by wukq** [comment]
因为限流的实现是基于redis的，所以性能完成取决于redis的性能，如果是更高的qps就不推荐用中心化的限流，可以考虑使用单节点内存限流。

**Comment by wukq** [comment]
> 更高的 qps 会有什么问题呢

因为限流的实现是基于redis的，所以性能完成取决于redis的性能，如果是更高的qps就不推荐用中心化的限流，可以考虑使用单节点内存限流。
